#License:Apache License 2.0
import os

def generate_markdown_report(result_summary, metrics, config, output_dir, run_id):
    """
    Create a detailed Markdown report.
    """
    
    def format_val(val, fmt="{:.2f}"):
        if val is None: return "N/A"
        return fmt.format(val)

    md = f"""# HRV Coach Pro v2.1 Report
**Run ID:** {run_id}
**Record:** {config.get('record_id', 'N/A')} ({config.get('dataset', 'N/A')})
**Date:** {pd.Timestamp.now()}

## 1. Executive Summary
**Quality Grade:** {result_summary.get('grade', 'N/A')}
**Final Strategy:** {result_summary.get('strategy_used', 'N/A')} (Preprocess: {result_summary.get('preprocess', 'N/A')}, Detect: {result_summary.get('detector', 'N/A')})

{result_summary.get('reason', '')}

## 2. HRV Metrics
| Metric | Value | Unit |
| :--- | :--- | :--- |
| **Time Domain** | | |
| Mean NN | {format_val(metrics.get('mean_nn', None))} | ms |
| SDNN | {format_val(metrics.get('sdnn', None))} | ms |
| RMSSD | {format_val(metrics.get('rmssd', None))} | ms |
| pNN50 | {format_val(metrics.get('pnn50', None))} | % |
| **Frequency Domain** | | |
| LF Power | {format_val(metrics.get('lf_power', None))} | ms² |
| HF Power | {format_val(metrics.get('hf_power', None))} | ms² |
| LF/HF Ratio | {format_val(metrics.get('lf_hf_ratio', None))} | - |

## 3. Agent Decision Log
The agent attempted the following strategies before settling on the best result:

"""
    # Log entries
    if 'history' in result_summary:
        for attempt in result_summary['history']:
            md += f"- **Step {attempt['step']}**: Tried {attempt['strategy']} + {attempt['method']}. Result: Grade {attempt['grade']} ({attempt['reason']})\n"
            
    md += """
## 4. Visualizations
![Analysis Plots](plots.png)

---
*Generated by HRV Coach Pro v2.1*
"""
    
    report_path = os.path.join(output_dir, "report.md")
    with open(report_path, "w") as f:
        f.write(md)
        
    return report_path

import pandas as pd
